Switch to using composite actions

diff --git a/.github/actions/process-values/action.yml b/.github/actions/process-values/action.yml
--- a/.github/actions/process-values/action.yml
+++ b/.github/actions/process-values/action.yml
@@ -1,5 +1,5 @@
 name: Process Values
-description: Handle MSA processing, run Python scripts, and verify Helm templates
+description: Handle MSA processing, run Python scripts, and verify Helm templates.
 inputs:
   env_type:
     description: 'Environment type (prod, dev, uat)'
@@ -10,14 +10,14 @@ inputs:
   msa_numbers_prefix:
     description: 'Prefix for the msa_numbers file'
     required: true
-  gitops_repo_path:
-    description: 'Path to the GitOps repository'
+  review_gitops_path:
+    description: 'Path to the Review-GitOps repository'
     required: true
   terraform_repo_path:
     description: 'Path to the Terraform repository'
     required: true
-  review_gitops_path:
-    description: 'Path to the Review GitOps repository'
+  argocd_gitops_path:
+    description: 'Path to the ArgoCD-GitOps repository'
     required: true
   github_token:
     description: 'GitHub token for pushing changes'
@@ -28,6 +28,7 @@ runs:
   steps:
     - name: Extract MSA Numbers
       run: |
+        cd ${{ inputs.terraform_repo_path }}
         regions_envs=$(cat ${{ inputs.regions_envs_file }} | jq -r '.[] | @base64')
         for region_env in $regions_envs; do
           _jq() {
@@ -39,7 +40,6 @@ runs:
 
           if [[ "$ENV" == "${{ inputs.env_type }}" ]]; then
             echo "Processing $ENV/$REGION"
-            cd ${{ inputs.terraform_repo_path }}
             git fetch origin
             git checkout $BRANCH
             git pull origin $BRANCH
@@ -47,15 +47,13 @@ runs:
             MAIN_TF="${ENV}/$REGION/99_clients/main.tf"
             echo "Extracting MSA numbers for $ENV/$REGION from $MAIN_TF"
             grep 'module.MSA' $MAIN_TF | egrep -o '[0-9]+' | sort -u > ../msa_numbers_${{ inputs.env_type }}_${REGION}.txt
-            cd ..
-          else
-            echo "Skipping $ENV/$REGION as it does not match the env_type ${{ inputs.env_type }}"
           fi
         done
       shell: bash
 
     - name: Handle Symlinks for Overridden and Non-Overridden MSAs
       run: |
+        cd ${{ inputs.argocd_gitops_path }}
         regions_envs=$(cat ${{ inputs.regions_envs_file }} | jq -r '.[] | @base64')
         for region_env in $regions_envs; do
           _jq() {
@@ -65,12 +63,12 @@ runs:
           ENV=$(_jq '.env')
 
           if [[ "$ENV" == "${{ inputs.env_type }}" ]]; then
-            ALL_MSAS=$(cat msa_numbers_${{ inputs.env_type }}_${REGION}.txt | sort -u)
+            ALL_MSAS=$(cat ../msa_numbers_${{ inputs.env_type }}_${REGION}.txt | sort -u)
             OVERRIDDEN_MSAS=$(yq eval '.msas | keys' ${{ inputs.review_gitops_path }}/${ENV}/${REGION}/versions.yaml | grep -o '[0-9]\+')
 
             for MSA in $ALL_MSAS; do
-              FILE="${{ inputs.gitops_repo_path }}/review/${ENV}/${REGION}/$MSA.yaml"
-              DEFAULT_VALUES_FILE="${{ inputs.gitops_repo_path }}/review/${ENV}/${REGION}/default_values.yaml"
+              FILE="${{ inputs.argocd_gitops_path }}/review/${ENV}/${REGION}/$MSA.yaml"
+              DEFAULT_VALUES_FILE="${{ inputs.argocd_gitops_path }}/review/${ENV}/${REGION}/default_values.yaml"
 
               if echo "$OVERRIDDEN_MSAS" | grep -q "$MSA"; then
                 if [ -L $FILE ]; then
@@ -85,14 +83,13 @@ runs:
                 fi
               fi
             done
-          else
-            echo "Skipping $ENV/$REGION as it does not match the env_type ${{ inputs.env_type }}"
           fi
         done
       shell: bash
 
     - name: Run Python Script to Generate Values
       run: |
+        cd ${{ inputs.review_gitops_path }}
         regions_envs=$(cat ${{ inputs.regions_envs_file }} | jq -r '.[] | @base64')
         for region_env in $regions_envs; do
           _jq() {
@@ -102,67 +99,53 @@ runs:
           ENV=$(_jq '.env')
           if [[ "$ENV" == "${{ inputs.env_type }}" ]]; then
             echo "Running Python script for $ENV/$REGION"
-            python ${{ inputs.review_gitops_path }}/.github/actions/scripts/process_values.py ${{ inputs.review_gitops_path }}/${ENV}/${REGION}/versions.yaml ${{ inputs.gitops_repo_path }}/review/${ENV}/${REGION}
-          else
-            echo "Skipping Python script for $ENV/$REGION as it does not match the env_type ${{ inputs.env_type }}"
+            python ${{ inputs.review_gitops_path }}/.github/actions/scripts/process_values.py ${{ inputs.review_gitops_path }}/${ENV}/${REGION}/versions.yaml ${{ inputs.argocd_gitops_path }}/review/${ENV}/${REGION}
           fi
         done
       shell: bash
 
-    - name: Verify Helm Templates and Tags
-      run: |
-        set -x
-        pwd
-        cd ${{ inputs.gitops_repo_path }}
-        pwd
-        echo "Running git diff to find modified files..."
-        git diff --name-only | grep 'review/' > ../modified_files_raw.txt
-    
-        if [ ! -s ../modified_files_raw.txt ]; then
-          echo "No modified files found matching 'review/'. Exiting."
-          exit 0
-        fi
-    
-        # Process the modified files to add the full path
-        sed "s|^|$(pwd)/|" ../modified_files_raw.txt > ../modified_files.txt
-        cat ../modified_files.txt
-        
-        echo "Running helm repo add and update..."
-        helm repo add redon-chart-repo https://redon-cdn.s3.amazonaws.com/
-        helm repo update
-    
-        while IFS= read -r values_file; do
-          echo "Processing $values_file"
-          helm template redon-chart-repo/argopoc --values $values_file > rendered_template.yaml
-    
-          grep 'image:' rendered_template.yaml | while read -r line ; do
-            repo=$(echo $line | awk -F: '{print $2}' | sed 's| //||g' | awk -F/ '{print $2}')
-            tag=$(echo $line | awk -F: '{print $3}')
-    
-            if [ -z "$repo" ] || [ -z "$tag" ]; then
-              echo "Failed to parse repo or tag from line: $line"
-              exit 1
-            fi
-    
-            echo "Checking tag $tag for repository $repo in file $values_file"
-            # Uncomment the following line to actually check in AWS ECR
-            # aws ecr describe-images --repository-name $repo --image-ids imageTag=$tag || exit 1
-            echo "Tag $tag exists in ECR for repo $repo"
-          done
-        done < ../modified_files.txt
-      shell: bash
-
-
-
-    - name: Show Differences
-      run: |
-        cd ${{ inputs.gitops_repo_path }}
-        git diff
-      shell: bash
+#    - name: Verify Helm Templates and Tags
+#      run: |
+#        cd ${{ inputs.argocd_gitops_path }}
+#        echo "Running git diff to find modified files..."
+#        git diff --name-only | grep 'review/' > ../modified_files_raw.txt
+#
+#        if [ ! -s ../modified_files_raw.txt ]; then
+#          echo "No modified files found matching 'review/'. Exiting."
+#          exit 0
+#        fi
+#
+#        sed "s|^|$(pwd)/|" ../modified_files_raw.txt > ../modified_files.txt
+#        cat ../modified_files.txt
+#
+#        echo "Running helm repo add and update..."
+#        helm repo add redon-chart-repo https://redon-cdn.s3.amazonaws.com/
+#        helm repo update
+#
+#        while IFS= read -r values_file; do
+#          echo "Processing $values_file"
+#          helm template redon-chart-repo/argopoc --values $values_file > rendered_template.yaml
+#
+#          grep 'image:' rendered_template.yaml | while read -r line ; do
+#            repo=$(echo $line | awk -F: '{print $2}' | sed 's| //||g' | awk -F/ '{print $2}')
+#            tag=$(echo $line | awk -F: '{print $3}')
+#
+#            if [ -z "$repo" ] || [ -z "$tag" ]; then
+#              echo "Failed to parse repo or tag from line: $line"
+#              exit 1
+#            fi
+#
+#            echo "Checking tag $tag for repository $repo in file $values_file"
+#            # Uncomment the following line to actually check in AWS ECR
+#            # aws ecr describe-images --repository-name $repo --image-ids imageTag=$tag || exit 1
+#            echo "Tag $tag exists in ECR for repo $repo"
+#          done
+#        done < ../modified_files.txt
+#      shell: bash
 
     - name: Commit and Push Updates
       run: |
-        cd ${{ inputs.gitops_repo_path }}
+        cd ${{ inputs.argocd_gitops_path }}
         git config user.email "your_email@example.com"
         git config user.name "Your Name"
         git add .
