update dev

diff --git a/.github/workflows/argocd-gitops.yaml b/.github/workflows/argocd-gitops.yaml
--- a/.github/workflows/argocd-gitops.yaml
+++ b/.github/workflows/argocd-gitops.yaml
@@ -417,16 +417,24 @@ jobs:
         run: |
           
           helm repo add redon-chart-repo https://redon-cdn.s3.amazonaws.com/
+          helm repo update
+          
           while IFS= read -r values_file; do
             echo "Processing $values_file"
             helm template redon-chart-repo/argopoc --values $values_file > rendered_template.yaml
       
-            # Extract image tags from the rendered template
-            tags=$(grep 'image:' rendered_template.yaml | awk -F: '{print $3}')
-            for tag in $tags; do
-              # Check if tag exists in ECR
-              #aws ecr describe-images --repository-name $REPO_NAME --image-ids imageTag=$tag || exit 1
-              echo "Tag $tag exists in ECR for repo $REPO_NAME"
+            grep 'image:' rendered_template.yaml | while read -r line ; do
+              repo=$(echo $line | awk -F: '{print $2}' | sed 's| //||g' | awk -F/ '{print $2}')
+              tag=$(echo $line | awk -F: '{print $3}')
+              
+              if [ -z "$repo" ] || [ -z "$tag" ]; then
+                echo "Failed to parse repo or tag from line: $line"
+                exit 1
+              fi
+
+              echo "Checking tag $tag for repository $repo in file $values_file"
+              #aws ecr describe-images --repository-name $repo --image-ids imageTag=$tag || exit 1
+              echo "Tag $tag exists in ECR for repo $repo"
             done
           done < modified_files.txt
           
