update dev

diff --git a/.github/workflows/argocd-gitops.yaml b/.github/workflows/argocd-gitops.yaml
--- a/.github/workflows/argocd-gitops.yaml
+++ b/.github/workflows/argocd-gitops.yaml
@@ -204,6 +204,41 @@ jobs:
             fi
           done
 
+      - name: Check filechanges for Image verification
+        run: |
+          cd argocd-gitops
+          git diff --name-only | grep 'review/' | sed "s|^|$(pwd)/|" > ../modified_files.txt
+          cat ../modified_files.txt
+
+      - name: Install Helm
+        run: |
+          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+
+      - name: Generate Helm Template and Verify Tags
+        run: |
+          
+          helm repo add redon-chart-repo https://redon-cdn.s3.amazonaws.com/
+          helm repo update
+          
+          while IFS= read -r values_file; do
+            echo "Processing $values_file"
+            helm template redon-chart-repo/argopoc --values $values_file > rendered_template.yaml
+      
+            grep 'image:' rendered_template.yaml | while read -r line ; do
+              repo=$(echo $line | awk -F: '{print $2}' | sed 's| //||g' | awk -F/ '{print $2}')
+              tag=$(echo $line | awk -F: '{print $3}')
+              
+              if [ -z "$repo" ] || [ -z "$tag" ]; then
+                echo "Failed to parse repo or tag from line: $line"
+                exit 1
+              fi
+
+              echo "Checking tag $tag for repository $repo in file $values_file"
+              #aws ecr describe-images --repository-name $repo --image-ids imageTag=$tag || exit 1
+              echo "Tag $tag exists in ECR for repo $repo"
+            done
+          done < modified_files.txt
+
       - name: Show Differences
         run: |
           cd argocd-gitops
@@ -403,7 +438,7 @@ jobs:
             fi
           done
 
-      - name: Show Differences
+      - name: Check filechanges for Image verification
         run: |
           cd argocd-gitops
           git diff --name-only | grep 'review/' | sed "s|^|$(pwd)/|" > ../modified_files.txt
