add new workflow

diff --git a/.github/workflows/review-gitops.yaml b/.github/workflows/review-gitops.yaml
--- a/.github/workflows/review-gitops.yaml
+++ b/.github/workflows/review-gitops.yaml
@@ -36,14 +36,17 @@ jobs:
       id: determine-directory
       run: |
         BRANCH_NAME=$(git -C terraform rev-parse --abbrev-ref HEAD)
+        echo "Branch Name: $BRANCH_NAME"
         if [[ "$BRANCH_NAME" == "develop" ]]; then
           echo "dir=argocd-gitops/dev/us-east-1" >> $GITHUB_ENV
-        elif [[ "$BRANCH_NAME" == "uat" ]]; then
+        elif [[ "$BRANCH_NAME" == "staging" ]]; then
           echo "dir=argocd-gitops/uat/eu-west-1" >> $GITHUB_ENV
-        elif [[ "$BRANCH_NAME" == "prod" ]]; then
+        elif [[ "$BRANCH_NAME" == "production" ]]; then
           echo "dir=argocd-gitops/prod/us-east-1" >> $GITHUB_ENV
           echo "dir2=argocd-gitops/prod/us-west-1" >> $GITHUB_ENV
         fi
+        echo "Directory: ${{ env.dir }}"
+        echo "Directory2: ${{ env.dir2 }}"
 
     - name: Create/Update YAML Files in ArgoCD-GitOps
       run: |
@@ -52,10 +55,16 @@ jobs:
           echo "Processing MSA $MSA"
           DIRECTORY="${{ env.dir }}"
           FILE="$DIRECTORY/$MSA.yaml"
-          
+
+          if [ -z "$DIRECTORY" ]; then
+            echo "Error: DIRECTORY is not set"
+            exit 1
+          fi
+
           # Ensure the directory exists
           mkdir -p $DIRECTORY
 
+          # Check for MSA overrides in review-gitops
           if grep -q "$MSA" review-gitops/dev/us-east-1/versions.yaml; then
             OVERRIDE_VERSION=$(grep "$MSA" review-gitops/dev/us-east-1/versions.yaml | awk '{print $2}')
             echo "default_all: 2024.7.29\nmsas:\n   $MSA:\n          search: $OVERRIDE_VERSION" > $FILE
